# html lang
language:

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tag
  Projects: /projects
  Contact: /contact
  About: /about

# Miscelaneous
favicon: /img/favicon.ico
logo: Nanbo

# stylesheets loaded in the <head>
stylesheets:
- /css/glow.css
- /lib/highlight/highlight-gruvbox-dark.css
- /fonts/font-awesome-4.7.0/css/font-awesome.min.css
# scripts loaded in the end of the body
scripts:
- /js/glow.js

lib:
- /lib/jquery-3.2.1.min.js
- /lib/highlight/highlight.pack.js
- /lib/highlight/activeHighlight.js
- /lib/backToTop.js
