# html lang
# glow theme support two languages: Chinese and English,you can change language from theme/languages .yml file name just like this:
# language: zh-cmn-Hans
language: zh-cmn-Hans

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tag
  Projects: /projects
  Contact: /contact
  About: /about

# Social Links.
# Usage: `Key: permalink || icon`
# Key is the link label showing to end users.
# Value before `||` delimeter is the target permalink.
# Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, globe icon will be loaded.
social:
  #GitHub: https://github.com/yourname || github
  #E-Mail: mailto:yourname@gmail.com || envelope
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype



# Miscelaneous
# favicon can configured by relative link by copy file to theme/img directory,just like this:
# favicon: /img/favicon.icon
# also can add permalink of your cdn or cloud link,just link this:
# favicon: http://ono38scfe.bkt.clouddn.com/favicon_tree.ico
logo: Nanbo
# To get or check favicons visit: https://realfavicongenerator.net
# Put your favicons into `hexo-site/source/` (recommend) or `hexo-site/themes/next/source/images/` directory.

# Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory.
# And if you want to place your icons in `hexo-site/source/` root directory, you must remove `/images` prefix from pathes.

# For example, you put your favicons into `hexo-site/source/images` directory.
# Then need to rename & redefine they on any other names, otherwise icons from Next will rewrite your custom icons in Hexo.
favicon: http://ono38scfe.bkt.clouddn.com/favicon_tree.ico
###small: /images/favicon-16x16-next.png
#  medium: /images/favicon-32x32-next.png
#  apple_touch_icon: /images/apple-touch-icon-next.png
#  safari_pinned_tab: /images/logo.svg
#  android_manifest: /images/manifest.json
#  ms_browserconfig: /images/browserconfig.xml
#android_chrome_color:

# stylesheets loaded in the <head> use url just link this:
# - /fonts/font-awesome-4.7.0/css/font-awesome.min.css
stylesheets:

# scripts loaded in the end of the body

scripts:

lib:


# Google Analytics
#google_analytics:

# Baidu Analytics ID
#baidu_analytics:


# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
#bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# qihu_site_verification:
# baidu_site_verification:

# version:
