# html lang
# glow theme support two languages: Chinese and English,you can change language from theme/languages .yml file name just like this:
# language: zh-cmn-Hans
language: zh-cmn-Hans

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tag
  Projects: /projects
  Contact: /contact
  About: /about

# Miscelaneous
# favicon can configured by relative link by copy file to theme/img directory,just like this:
# favicon: /img/favicon.icon
# also can add permalink of your cdn or cloud link,just link this:
# favicon: http://ono38scfe.bkt.clouddn.com/favicon_tree.ico
favicon: /img/favicon.ico
logo: Nanbo

# stylesheets loaded in the <head> use url just link this:
# - /fonts/font-awesome-4.7.0/css/font-awesome.min.css
stylesheets:

# scripts loaded in the end of the body

scripts:

lib:
